export const ACCOUNTS_LIST_REQUEST = 'ACCOUNTS_TYPE_REQUEST';
export const ACCOUNTS_LIST_RECEIVED = 'ACCOUNTS_TYPE_RECEIVED';
export const ACCOUNTS_LIST_ERROR = 'ACCOUNTS_TYPE_ERROR';

export const ASSETS_LIST_REQUEST = 'ASSETS_TYPE_REQUEST';
export const ASSETS_LIST_RECEIVED = 'ASSETS_TYPE_RECEIVED';
export const ASSETS_LIST_ERROR = 'ASSETS_TYPE_ERROR';

export const COINGECKOCRYPTOS_LIST_REQUEST = 'COINGECKOCRYPTOS_TYPE_REQUEST';
export const COINGECKOCRYPTOS_LIST_RECEIVED = 'COINGECKOCRYPTOS_TYPE_RECEIVED';
export const COINGECKOCRYPTOS_LIST_ERROR = 'COINGECKOCRYPTOS_TYPE_ERROR';

export const COINGECKOEXCHANGES_LIST_REQUEST = 'COINGECKOEXCHANGES_TYPE_REQUEST';
export const COINGECKOEXCHANGES_LIST_RECEIVED = 'COINGECKOEXCHANGES_TYPE_RECEIVED';
export const COINGECKOEXCHANGES_LIST_ERROR = 'COINGECKOEXCHANGES_TYPE_ERROR';

export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS';
export const USER_LOGOUT = 'USER_LOGOUT';
export const USER_SET_ID = 'USER_SET_ID';

export const USER_PROFILE_REQUEST = 'USER_PROFILE_REQUEST';
export const USER_PROFILE_RECEIVED = 'USER_PROFILE_RECEIVED';
export const USER_PROFILE_ERROR = 'USER_PROFILE_ERROR';

